// @vitest-environment node
import { readFileSync } from 'fs'
import { describe, expect, it } from 'vitest'

describe('chat message mobile layout guards', () => {
  it('keeps chat message containers shrinkable on narrow screens', () => {
    const chatPanel = readFileSync('packages/client/src/components/hermes/chat/ChatPanel.vue', 'utf8')
    const messageList = readFileSync('packages/client/src/components/hermes/chat/MessageList.vue', 'utf8')
    const virtualList = readFileSync('packages/client/src/components/hermes/chat/VirtualMessageList.vue', 'utf8')
    const messageItem = readFileSync('packages/client/src/components/hermes/chat/MessageItem.vue', 'utf8')
    const markdownRenderer = readFileSync('packages/client/src/components/hermes/chat/MarkdownRenderer.vue', 'utf8')
    const groupChatPanel = readFileSync('packages/client/src/components/hermes/group-chat/GroupChatPanel.vue', 'utf8')
    const groupMessageList = readFileSync('packages/client/src/components/hermes/group-chat/GroupMessageList.vue', 'utf8')
    const groupMessageItem = readFileSync('packages/client/src/components/hermes/group-chat/GroupMessageItem.vue', 'utf8')

    expect(chatPanel).toContain('.chat-panel')
    expect(chatPanel).toContain('min-width: 0;')
    expect(chatPanel).toContain('.chat-content-wrapper')
    expect(chatPanel).toContain('max-width: 100%;')
    expect(chatPanel).toContain('class="header-title-stack"')
    expect(chatPanel).toContain("'header-title-stack--with-workspace'")
    expect(chatPanel).toContain('showDrawerRainbow')
    expect(chatPanel).toContain("'drawer-button-wrapper--rainbow'")
    expect(chatPanel).toContain('.drawer-button-wrapper--rainbow')
    expect(chatPanel).toContain('settingsStore.display.show_drawer_rainbow !== false')
    expect(chatPanel).toContain('.header-title-stack--with-workspace .header-session-title')
    expect(chatPanel).toContain('font-size: 13px;')
    expect(chatPanel).toContain('font-size: 10px;')
    expect(chatPanel).toMatch(/@media \(max-width: \$breakpoint-mobile\)[\s\S]*?\.header-session-title\s*\{[\s\S]*?display:\s*inline-block;/)
    expect(chatPanel).not.toContain('.header-session-title {\n    display: none;')

    expect(messageList).toContain('--tool-mascot-height: 213px;')
    expect(messageList).toContain('height: var(--tool-mascot-height);')
    expect(messageList).toContain('min-height: var(--tool-mascot-height);')
    expect(messageList).toContain('&.streaming-indicator--no-mascot::before')
    expect(messageList).toContain('flex: 0 0 4px;')
    expect(messageList).toContain('box-shadow: 0 0 18px rgba(var(--accent-primary-rgb), 0.16);')
    expect(messageList).toContain('animation: hidden-mascot-activity-bar 5.6s ease-in-out infinite;')
    expect(messageList).toContain('@keyframes hidden-mascot-activity-bar')
    expect(messageList).toContain('@media (prefers-reduced-motion: reduce)')
    expect(messageList).toContain('.tool-calls-panel')
    expect(messageList).toContain('.tool-call-preview')
    expect(messageList).toContain('function toolCallPreview')
    expect(messageList).toContain('function toolCallTitle')
    expect(messageList).toContain(':title="toolCallTitle(tc)"')
    expect(messageList).toContain('max-width: 300px;')
    expect(messageList).toContain('max-width: min(760px, 72vw);')
    expect(messageList).toContain('flex: 1 1 auto;')
    expect(messageList).toContain('min-width: 0;')
    expect(messageList).toContain('width: 100%;')
    expect(messageList).toContain('max-width: none;')

    expect(virtualList).toContain('.virtual-message-list-host')
    expect(virtualList).toContain('.virtual-row')
    expect(virtualList).toContain('min-width: 0;')
    expect(virtualList).toContain('max-width: 100%;')

    expect(messageItem).toContain('.msg-body')
    expect(messageItem).toContain('.msg-content')
    expect(messageItem).toContain('.message-bubble')
    expect(messageItem).toContain('overflow-wrap: anywhere;')

    expect(markdownRenderer).toContain('.markdown-body')
    expect(markdownRenderer).toContain('width: 100%;')
    expect(markdownRenderer).toContain('code:not(.hljs)')
    expect(markdownRenderer).toContain('white-space: pre-wrap;')
    expect(markdownRenderer).toContain('markdown-table-wrapper')
    expect(markdownRenderer).toContain('markdown-table-copy-btn')
    expect(markdownRenderer).toContain('data-markdown-table-copy')
    expect(markdownRenderer).toContain('min-width: 120px;')
    expect(markdownRenderer).toContain('max-width: 240px;')
    expect(markdownRenderer).toContain('vertical-align: top;')
    expect(markdownRenderer).toContain('white-space: normal;')
    expect(markdownRenderer).toContain('overflow-wrap: anywhere;')
    expect(markdownRenderer).toContain('word-break: break-word;')

    expect(groupChatPanel).toContain('.group-chat-panel')
    expect(groupChatPanel).toContain('min-width: 0;')
    expect(groupChatPanel).toContain('max-width: 100%;')

    expect(groupMessageList).toContain('.group-message-list')
    expect(groupMessageList).toContain('min-width: 0;')
    expect(groupMessageList).toContain('max-width: 100%;')

    expect(groupMessageItem).toContain('.group-message')
    expect(groupMessageItem).toContain('.msg-body')
    expect(groupMessageItem).toContain('.msg-content')
    expect(groupMessageItem).toContain('overflow-wrap: anywhere;')
  })
})
